export const siteConfig = {
	title: 'FreeTheAi',
	description:
		'FreeTheAi is a free AI API with Discord key signup, live free models, OpenAI-compatible chat completions, streaming, and tool calling.',
	site: 'https://freetheai.xyz',
	author: {
		name: 'FreeTheAi',
		url: 'https://freetheai.xyz',
	},
	socials: {
		discord: 'https://discord.gg/secrets',
		github: 'https://github.com/vibheksoni/free-ai',
		api: 'https://api.freetheai.xyz',
	},
	defaults: {
		locale: 'en_US',
		twitterCard: 'summary_large_image',
		ogImage: '/og-card.svg',
		keywords: [
			'free ai api',
			'openai compatible api',
			'free openai api',
			'free llm api',
			'tool calling api',
			'streaming ai api',
			'windsurf api',
			'swe-1.6 api',
			'kimi k2.6 api',
			'glm 5.1 api',
			'glm api',
			'free glm api',
			'free gpt oss api',
			'chat completions api',
			'discord api key signup',
			'free models api',
			'ai api without daily limit',
			'developer ai tools',
		],
	},
};
